<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["orders", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h4>
        Edit orders
    </h4>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "orders/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldUserId" class="col-sm-2 control-label">User</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["user_id", "type" => "number", "class" => "form-control", "id" => "fieldUserId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldProducts" class="col-sm-2 control-label">Products</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["products", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldProducts"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
