<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<div class="container">
    <div class="center-block">
        <div class="row">
            <div class="page-header">
                <h4>
                    Search orderss
                </h4>
                <p>
                    <?php echo $this->tag->linkTo(["orders/new", "Create orders"]) ?>
                </p>
            </div>
        </div>

        <!--            --><?php //echo $this->getContent(); ?>

        <div class="container">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">User</th>
                    <th scope="col">Products</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                <?php
                foreach ($orders as $order) { ?>
                    <tr>
                        <th><?php echo $order->id; ?></th>
                        <td><?php echo $order->Users->username; ?></td>
                        <td><?php foreach ($order->Products as $product){
                                    echo $product-> product_name . " ";
                                }?>
                        </td>
                        <td>--</td>
                    </tr>

                <?php } ?>

                </tbody>
            </table>
        </div>
    </div>
</div>