<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h4>
        Search products
    </h4>
    <p>
        <?php echo $this->tag->linkTo(["products/new", "Create products"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "products/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<!--<div class="form-group">-->
<!--    <label for="fieldId" class="col-sm-2 control-label">Id</label>-->
<!--    <div class="col-sm-10">-->
<!--        --><?php //echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
<!--    </div>-->
<!--</div>-->

<div class="form-group">
    <label for="fieldProductName" class="col-sm-2 control-label">Product name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["product_name", "size" => 30, "class" => "form-control", "id" => "fieldProductName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPrice" class="col-sm-2 control-label">Price</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["price", "size" => 30, "class" => "form-control", "id" => "fieldPrice"]) ?>
    </div>
</div>

<!--<div class="form-group">-->
<!--    <label for="fieldSale" class="col-sm-2 control-label">Sale</label>-->
<!--    <div class="col-sm-10">-->
<!--        --><?php //echo $this->tag->textField(["sale", "size" => 30, "class" => "form-control", "id" => "fieldSale"]) ?>
<!--    </div>-->
<!--</div>-->


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
