<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["products", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h4>
        Create products
    </h4>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "products/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldProductName" class="col-sm-2 control-label">Product name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["product_name", "size" => 30, "class" => "form-control", "id" => "fieldProductName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPrice" class="col-sm-2 control-label">Price</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["price", "size" => 30, "class" => "form-control", "id" => "fieldPrice"]) ?>
    </div>
</div>

<!--<div class="form-group">-->
<!--    <label for="fieldSale" class="col-sm-2 control-label">Sale</label>-->
<!--    <div class="col-sm-10">-->
<!--        --><?php //echo $this->tag->textField(["sale", "size" => 30, "class" => "form-control", "id" => "fieldSale"]) ?>
<!--    </div>-->
<!--</div>-->


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
