<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["products/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["products/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h4>Search result</h4>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Product Of Name</th>
            <th>Price</th>
            <th>Sale</th>

<!--                <th></th>-->
<!--                <th></th>-->
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $product):?>
            <tr>
                <td><?php echo $product->id ?></td>
            <td><?php echo $product->product_name ?></td>
            <td><?php echo $product->price ?></td>
            <td><?php echo $product->sale == false ? 'No' : 'Yes'; ?></td>

<!--                <td>--><?php //echo $this->tag->linkTo(["products/edit/" . $product->getId(), "Edit"]); ?><!--</td>-->
<!--                <td>--><?php //echo $this->tag->linkTo(["products/delete/" . $product->getId(), "Delete"]); ?><!--</td>-->
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo(["products/search", "First", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["products/search?page=" . $page->before, "Previous", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["products/search?page=" . $page->next, "Next", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["products/search?page=" . $page->last, "Last", 'class' => 'page-link']) ?></li>
            </ul>
        </nav>
    </div>
</div>
